---
# ServiceMonitor para Prometheus Operator (opcional si usas Prometheus Operator)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-metrics
  namespace: default
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /stats/prometheus
      interval: 15s

---
# ServiceMonitor para Istio Envoy sidecar
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-mesh-metrics
  namespace: default
  labels:
    release: istio
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s
