---
apiVersion: batch/v1
kind: Job
metadata:
  name: oracle-init
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-oracle
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Esperando a que Oracle esté listo..."
              until nc -z oracle-db 1521; do
                echo "Oracle no está listo aún..."
                sleep 10
              done
              echo "Oracle está listo, esperando 60s adicionales para asegurar inicialización completa..."
              sleep 60
      containers:
        - name: init-database
          image: container-registry.oracle.com/database/free:latest
          command:
            - bash
            - -c
            - |
              echo "✅ Usuario GESTOCK ya existe. Ejecutando scripts restantes..."

              cd /tmp

              # Obtener archivos de scripts desde el host
              echo "📥 Descargando scripts de inicialización..."

              # Ejecutar cada script en orden
              for script_num in 02 03 04 05 06 07 08 09 999; do
                script_file="${script_num}-*.sql"
                echo "📄 Buscando script: ${script_file}"
                
                # Como no podemos montar archivos, vamos a ejecutar solo los más críticos inline
                case ${script_num} in
                  02)
                    echo "Creando secuencias..."
                    # Secuencias se pueden recrear si es necesario
                    ;;
                  03)
                    echo "Creando tablas..."
                    # Las tablas son críticas - necesitamos ejecutar el script completo
                    echo "⚠️  Por favor ejecutar manualmente: kubectl cp oracle-db/init-scripts/03-create-tables.sql POD:/tmp/ && ejecutar"
                    ;;
                  *)
                    echo "⏭️  Saltando ${script_file}"
                    ;;
                esac
              done

              echo "✅ Inicialización básica completada"
              echo "⚠️  NOTA: Las tablas deben crearse ejecutando los scripts manualmente"
