-- Conectar a la PDB FREEPDB1
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Verificar que estamos en la PDB correcta
SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS current_container FROM DUAL;

-- Crear usuario GESTOCK en la PDB
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER GESTOCK IDENTIFIED BY adminadmin';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -1920 THEN -- User already exists
         RAISE;
      END IF;
END;
/

-- Otorgar permisos al usuario en la PDB
GRANT CONNECT, RESOURCE TO GESTOCK;
GRANT CREATE SESSION TO GESTOCK;
GRANT CREATE TABLE TO GESTOCK;
GRANT CREATE SEQUENCE TO GESTOCK;
GRANT CREATE VIEW TO GESTOCK;
GRANT CREATE PROCEDURE TO GESTOCK;
GRANT CREATE TRIGGER TO GESTOCK;
GRANT CREATE SYNONYM TO GESTOCK;
GRANT CREATE TYPE TO GESTOCK;
GRANT UNLIMITED TABLESPACE TO GESTOCK;

-- Establecer el esquema por defecto
ALTER SESSION SET CURRENT_SCHEMA = GESTOCK;

-- Mensaje de confirmación
SELECT 'Usuario GESTOCK creado exitosamente en ' || SYS_CONTEXT('USERENV', 'CON_NAME') AS resultado FROM DUAL;