ALTER SESSION SET CONTAINER = FREEPDB1;

-- Cambiar al schema de GESTOCK
ALTER SESSION SET CURRENT_SCHEMA = GESTOCK;
--------------------------------------------------------
--  DDL for View VW_CLOSURE_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_CLOSURE_DETAILS" ("CLOSURE_ID", "HEADER_ID", "PRODUCT_NAME", "LOT_ID", "FINAL_STOCK", "CLOSURE_DATE") AS 
  SELECT 
    ic.CLOSURE_ID,
    ic.HEADER_ID,
    p.PRODUCT_NAME,
    l.LOT_ID,
    ic.FINAL_STOCK,
    ic.CLOSURE_DATE
FROM INVENTORY_CLOSURE ic
JOIN PRODUCTS p ON ic.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN BATCHES l ON ic.LOT_ID = l.LOT_ID
ORDER BY ic.HEADER_ID, p.PRODUCT_NAME
;
--------------------------------------------------------
--  DDL for View VW_CLOSURE_HEADER
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_CLOSURE_HEADER" ("HEADER_ID", "CLOSURE_DATE", "CLOSURE_MONTH", "CLOSURE_YEAR", "USER_NAME", "STATUS") AS 
  SELECT
  ch.HEADER_ID,
  ch.CLOSURE_DATE,
  ch.CLOSURE_MONTH,
  ch.CLOSURE_YEAR,
  u.NAME AS USER_NAME,
  ch.STATUS
FROM CLOSURE_HEADER ch
LEFT JOIN USERS u ON ch.USER_ID = u.USER_ID
ORDER BY ch.CLOSURE_DATE DESC
;
--------------------------------------------------------
--  DDL for View VW_HISTORICAL_MOVEMENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_HISTORICAL_MOVEMENTS" ("MOVEMENT_ID", "MOVEMENT_DATE", "PRODUCT_NAME", "MOVEMENT_TYPE", "MOVEMENT_REASON", "QUANTITY", "USER_NAME", "REFERENCE") AS 
  SELECT 
    im.movement_id,
    im.movement_date,
    p.product_name,
    im.movement_type,
    im.movement_reason,
    im.quantity,
    u.name AS user_name,
    im.reference
FROM inventory_movements im
JOIN products p ON im.product_id = p.product_id
JOIN users u ON im.user_id = u.user_id
;
--------------------------------------------------------
--  DDL for View VW_INCOME_BY_LOT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_INCOME_BY_LOT" ("LOT_ID", "LOT_CODE", "LOT_DESCRIPTION", "ENTRY_DATE", "PRODUCT_ID", "PRODUCT_CODE", "PRODUCT_NAME", "CATEGORY_NAME", "MEASUREMENT_NAME", "CURRENT_UNITS", "UNIT_PRICE", "TOTAL_VALUE", "PRODUCT_STATE", "LAST_UPDATE") AS 
  SELECT 
    b.LOT_ID,
    b.RFID_CODE AS LOT_CODE,
    b.DESCRIPTION AS LOT_DESCRIPTION,
    b.ENTRY_DATE,
    p.PRODUCT_ID,
    p.PRODUCT_CODE,
    p.PRODUCT_NAME,
    pc.CATEGORY_NAME,
    mt.MEASUREMENT_NAME,
    i.ACTUAL_STOCK AS CURRENT_UNITS,
    p.UNIT_PRICE,
    (i.ACTUAL_STOCK * p.UNIT_PRICE) AS TOTAL_VALUE,
    ps.STATE_NAME AS PRODUCT_STATE,
    i.UPDATED_AT AS LAST_UPDATE
FROM 
    BATCHES b
    INNER JOIN INVENTORY i ON b.LOT_ID = i.LOT_ID
    INNER JOIN PRODUCTS p ON i.PRODUCT_ID = p.PRODUCT_ID
    INNER JOIN PRODUCT_CATEGORIES pc ON p.CATEGORY_ID = pc.CATEGORY_ID
    INNER JOIN PRODUCT_STATES ps ON p.STATE_ID = ps.STATE_ID
    INNER JOIN MEASUREMENTS_TYPES mt ON p.MEASUREMENT_ID = mt.MEASUREMENT_ID
WHERE 
    ps.STATE_ID = 1  -- Solo productos activos
ORDER BY 
    b.ENTRY_DATE DESC,
    pc.CATEGORY_NAME ASC,
    p.PRODUCT_NAME ASC
;
--------------------------------------------------------
--  DDL for View VW_INVENTORY_CLOSURE_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_INVENTORY_CLOSURE_DETAILS" ("CLOSURE_ID", "CLOSURE_DATE", "FINAL_STOCK", "LOT_ID", "PRODUCT_NAME", "USER_NAME", "HEADER_ID") AS 
  SELECT 
    IC.CLOSURE_ID,
    IC.CLOSURE_DATE,
    IC.FINAL_STOCK,
    IC.LOT_ID,
    P.PRODUCT_NAME,
    U.NAME AS USER_NAME,
    IC.HEADER_ID
FROM GESTOCK.INVENTORY_CLOSURE IC
LEFT JOIN GESTOCK.PRODUCTS P
    ON IC.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN GESTOCK.USERS U
    ON IC.USER_ID = U.USER_ID
LEFT JOIN GESTOCK.CLOSURE_HEADER CH
    ON IC.HEADER_ID = CH.HEADER_ID
;
--------------------------------------------------------
--  DDL for View VW_INVENTORY_DETAIL
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_INVENTORY_DETAIL" ("CODIGO_PRODUCTO", "NOMBRE_PRODUCTO", "DESCRIPCION_PRODUCTO", "CATEGORIA_PRODUCTO", "STOCK_ACTUAL", "STOCK_MINIMO", "PRECIO_UNITARIO", "ESTADO_PRODUCTO", "LOT_ID", "TIPO_MEDIDA") AS 
  SELECT 
    PR.PRODUCT_CODE AS CODIGO_PRODUCTO,
    PR.PRODUCT_NAME AS NOMBRE_PRODUCTO,
    PR.PRODUCT_DESCRIPTION AS DESCRIPCION_PRODUCTO,
    CT.CATEGORY_NAME AS CATEGORIA_PRODUCTO,
    INV.ACTUAL_STOCK AS STOCK_ACTUAL,
    INV.MINIMUM_STOCK AS STOCK_MINIMO,
    PR.UNIT_PRICE AS PRECIO_UNITARIO,
    ST.STATE_NAME AS ESTADO_PRODUCTO,
    INV.LOT_ID AS LOT_ID,
    MT.MEASUREMENT_NAME AS TIPO_MEDIDA
FROM INVENTORY INV
JOIN PRODUCTS PR ON INV.PRODUCT_ID = PR.PRODUCT_ID
JOIN PRODUCT_CATEGORIES CT ON PR.CATEGORY_ID = CT.CATEGORY_ID
JOIN PRODUCT_STATES ST ON PR.STATE_ID = ST.STATE_ID
JOIN MEASUREMENTS_TYPES MT ON PR.MEASUREMENT_ID = MT.MEASUREMENT_ID
;
--------------------------------------------------------
--  DDL for View VW_INVENTORY_REPORT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_INVENTORY_REPORT" ("PRODUCT_ID", "PRODUCT_CODE", "PRODUCT_NAME", "PRODUCT_DESCRIPTION", "CATEGORY_NAME", "PRODUCT_STATE", "MEASUREMENT_NAME", "AVAILABLE_UNITS", "MINIMUM_STOCK", "UNIT_PRICE", "TOTAL_VALUE", "LOT_CODE", "LAST_UPDATE") AS 
  SELECT 
    p.PRODUCT_ID,
    p.PRODUCT_CODE,
    p.PRODUCT_NAME,
    p.PRODUCT_DESCRIPTION,
    pc.CATEGORY_NAME,
    ps.STATE_NAME AS PRODUCT_STATE,
    mt.MEASUREMENT_NAME,
    i.ACTUAL_STOCK AS AVAILABLE_UNITS,
    i.MINIMUM_STOCK,
    p.UNIT_PRICE,
    (i.ACTUAL_STOCK * p.UNIT_PRICE) AS TOTAL_VALUE,
    CAST(i.LOT_ID AS VARCHAR2(50)) AS LOT_CODE,
    i.UPDATED_AT AS LAST_UPDATE
FROM 
    PRODUCTS p
    INNER JOIN INVENTORY i ON p.PRODUCT_ID = i.PRODUCT_ID
    INNER JOIN PRODUCT_CATEGORIES pc ON p.CATEGORY_ID = pc.CATEGORY_ID
    INNER JOIN PRODUCT_STATES ps ON p.STATE_ID = ps.STATE_ID
    INNER JOIN MEASUREMENTS_TYPES mt ON p.MEASUREMENT_ID = mt.MEASUREMENT_ID
WHERE 
    ps.STATE_ID = 1  -- Solo productos activos
ORDER BY 
    pc.CATEGORY_NAME ASC,
    p.PRODUCT_NAME ASC
;
--------------------------------------------------------
--  DDL for View VW_SALES_BY_CATEGORY
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_SALES_BY_CATEGORY" ("CATEGORY_ID", "CATEGORY_NAME", "PRODUCT_ID", "PRODUCT_CODE", "PRODUCT_NAME", "CURRENT_STOCK", "MINIMUM_STOCK", "UNIT_PRICE", "UNITS_SOLD", "TOTAL_SALES_VALUE", "LAST_UPDATE") AS 
  SELECT 
    pc.CATEGORY_ID,
    pc.CATEGORY_NAME,
    p.PRODUCT_ID,
    p.PRODUCT_CODE,
    p.PRODUCT_NAME,
    i.ACTUAL_STOCK AS CURRENT_STOCK,
    i.MINIMUM_STOCK,
    p.UNIT_PRICE,
    -- Por ahora, calculamos las "ventas" como la diferencia entre stock mínimo esperado
    -- En el futuro esto vendría de una tabla de SALES o MOVEMENTS
    CASE 
        WHEN i.ACTUAL_STOCK < i.MINIMUM_STOCK 
        THEN (i.MINIMUM_STOCK - i.ACTUAL_STOCK)
        ELSE 0 
    END AS UNITS_SOLD,
    CASE 
        WHEN i.ACTUAL_STOCK < i.MINIMUM_STOCK 
        THEN (i.MINIMUM_STOCK - i.ACTUAL_STOCK) * p.UNIT_PRICE
        ELSE 0 
    END AS TOTAL_SALES_VALUE,
    i.UPDATED_AT AS LAST_UPDATE
FROM 
    PRODUCTS p
    INNER JOIN INVENTORY i ON p.PRODUCT_ID = i.PRODUCT_ID
    INNER JOIN PRODUCT_CATEGORIES pc ON p.CATEGORY_ID = pc.CATEGORY_ID
    INNER JOIN PRODUCT_STATES ps ON p.STATE_ID = ps.STATE_ID
WHERE 
    ps.STATE_ID = 1  -- Solo productos activos
ORDER BY 
    pc.CATEGORY_NAME ASC,
    CASE 
        WHEN i.ACTUAL_STOCK < i.MINIMUM_STOCK 
        THEN (i.MINIMUM_STOCK - i.ACTUAL_STOCK)
        ELSE 0 
    END DESC,
    p.PRODUCT_NAME ASC
;
--------------------------------------------------------
--  DDL for View VW_STOCK_ALERTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_STOCK_ALERTS" ("PRODUCT_ID", "PRODUCT_CODE", "PRODUCT_NAME", "PRODUCT_DESCRIPTION", "PRODUCT_CATEGORY", "CURRENT_STOCK", "MINIMUM_STOCK", "DEFICIT", "UNIT_PRICE", "PRODUCT_STATE", "MEASUREMENT_TYPE", "LOT_ID", "ALERT_DATE") AS 
  SELECT 
  p.PRODUCT_ID,
  p.PRODUCT_CODE,
  p.PRODUCT_NAME,
  p.PRODUCT_DESCRIPTION,
  pc.CATEGORY_NAME AS PRODUCT_CATEGORY,
  i.ACTUAL_STOCK AS CURRENT_STOCK,
  i.MINIMUM_STOCK,
  (i.MINIMUM_STOCK - i.ACTUAL_STOCK) AS DEFICIT,
  p.UNIT_PRICE,
  ps.STATE_NAME AS PRODUCT_STATE,
  mt.MEASUREMENT_NAME AS MEASUREMENT_TYPE,
  i.LOT_ID,
  i.UPDATED_AT AS ALERT_DATE
FROM INVENTORY i
INNER JOIN PRODUCTS p ON i.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN PRODUCT_CATEGORIES pc ON p.CATEGORY_ID = pc.CATEGORY_ID
LEFT JOIN PRODUCT_STATES ps ON p.STATE_ID = ps.STATE_ID
LEFT JOIN MEASUREMENTS_TYPES mt ON p.MEASUREMENT_ID = mt.MEASUREMENT_ID
WHERE i.ACTUAL_STOCK <= i.MINIMUM_STOCK
  AND p.STATE_ID = 1  -- Solo productos activos
ORDER BY 
  CASE 
    WHEN i.ACTUAL_STOCK = 0 THEN 1  -- Sin stock primero
    WHEN i.ACTUAL_STOCK < i.MINIMUM_STOCK THEN 2  -- Debajo del mínimo
    ELSE 3  -- Justo en el mínimo
  END,
  (i.MINIMUM_STOCK - i.ACTUAL_STOCK) DESC,  -- Mayor déficit primero
  p.PRODUCT_NAME ASC;

   COMMENT ON COLUMN "GESTOCK"."VW_STOCK_ALERTS"."PRODUCT_ID" IS 'ID único del producto';
   COMMENT ON COLUMN "GESTOCK"."VW_STOCK_ALERTS"."PRODUCT_CODE" IS 'Código del producto';
   COMMENT ON COLUMN "GESTOCK"."VW_STOCK_ALERTS"."PRODUCT_NAME" IS 'Nombre del producto';
   COMMENT ON COLUMN "GESTOCK"."VW_STOCK_ALERTS"."CURRENT_STOCK" IS 'Stock actual disponible';
   COMMENT ON COLUMN "GESTOCK"."VW_STOCK_ALERTS"."MINIMUM_STOCK" IS 'Stock mínimo establecido';
   COMMENT ON COLUMN "GESTOCK"."VW_STOCK_ALERTS"."DEFICIT" IS 'Cantidad que falta para alcanzar el stock mínimo';
   COMMENT ON COLUMN "GESTOCK"."VW_STOCK_ALERTS"."ALERT_DATE" IS 'Fecha de la última actualización de stock';
   COMMENT ON TABLE "GESTOCK"."VW_STOCK_ALERTS"  IS 'Vista de productos con stock igual o menor al mínimo (alertas activas)'
;
--------------------------------------------------------
--  DDL for View VW_USER_MANAGEMENT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "GESTOCK"."VW_USER_MANAGEMENT" ("USER_ID", "NAME", "EMAIL", "ROLE_ID", "ROLE_NAME", "STATE_ID", "STATE_NAME") AS 
  SELECT 
  u.USER_ID,
  u.NAME,
  u.EMAIL,
  u.ROLE_ID,
  r.ROLE_NAME,
  u.STATE_ID,
  s.STATE_NAME
FROM USERS u
LEFT JOIN ROLES r ON u.ROLE_ID = r.ROLE_ID
LEFT JOIN USER_STATES s ON u.STATE_ID = s.STATE_ID;

   COMMENT ON COLUMN "GESTOCK"."VW_USER_MANAGEMENT"."USER_ID" IS 'ID único del usuario';
   COMMENT ON COLUMN "GESTOCK"."VW_USER_MANAGEMENT"."NAME" IS 'Nombre completo del usuario';
   COMMENT ON COLUMN "GESTOCK"."VW_USER_MANAGEMENT"."EMAIL" IS 'Email del usuario';
   COMMENT ON COLUMN "GESTOCK"."VW_USER_MANAGEMENT"."ROLE_ID" IS 'ID del rol asignado';
   COMMENT ON COLUMN "GESTOCK"."VW_USER_MANAGEMENT"."ROLE_NAME" IS 'Nombre del rol (ADMIN, JEFE DE ALMACEN, OPERARIO)';
   COMMENT ON COLUMN "GESTOCK"."VW_USER_MANAGEMENT"."STATE_ID" IS 'ID del estado del usuario';
   COMMENT ON COLUMN "GESTOCK"."VW_USER_MANAGEMENT"."STATE_NAME" IS 'Nombre del estado (Activo, Inactivo)';
   COMMENT ON TABLE "GESTOCK"."VW_USER_MANAGEMENT"  IS 'Vista para gestión de usuarios con roles y estados'
;