ALTER SESSION SET CONTAINER = FREEPDB1;ALTER SESSION SET CONTAINER = FREEPDB1;



-- Cambiar al schema de GESTOCK-- Cambiar al schema de GESTOCK

ALTER SESSION SET CURRENT_SCHEMA = GESTOCK;ALTER SESSION SET CURRENT_SCHEMA = GESTOCK;



----------------------------------------------------------------------------------------------------------------

--  DDL for Index IDX_MOVEMENTS_PRODUCT_PART (LOCAL PARTITIONED)--  DDL for Index IDX_MOVEMENTS_PRODUCT_PART

----------------------------------------------------------------------------------------------------------------

CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_PRODUCT_PART" ON "GESTOCK"."INVENTORY_MOVEMENTS" ("PRODUCT_ID") LOCAL;

  CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_PRODUCT_PART" ON "GESTOCK"."INVENTORY_MOVEMENTS" ("PRODUCT_ID") 

--------------------------------------------------------  PCTFREE 10 INITRANS 2 MAXTRANS 255 

--  DDL for Index PK_INVENTORY_MOVEMENTS  STORAGE(

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL

CREATE UNIQUE INDEX "GESTOCK"."PK_INVENTORY_MOVEMENTS" ON "GESTOCK"."INVENTORY_MOVEMENTS" ("MOVEMENT_ID", "MOVEMENT_DATE"); (PARTITION "P_2015" NOCOMPRESS 

  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--  DDL for Index IDX_PK_LOT_ID  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_LOT_ID" ON "GESTOCK"."BATCHES" ("LOT_ID");  TABLESPACE "TBS_GESTOCK_INDEX" , 

 PARTITION "P_2016" NOCOMPRESS 

--------------------------------------------------------  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

--  DDL for Index IDX_SALES_STATE  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--------------------------------------------------------  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

CREATE INDEX "GESTOCK"."IDX_SALES_STATE" ON "GESTOCK"."SALES" ("SALE_STATE_ID");  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "TBS_GESTOCK_INDEX" , 

-------------------------------------------------------- PARTITION "P_2017" NOCOMPRESS 

--  DDL for Index IDX_PK_CLOSURE_ID_PART  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_CLOSURE_ID_PART" ON "GESTOCK"."INVENTORY_CLOSURE" ("CLOSURE_ID");  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--------------------------------------------------------  TABLESPACE "TBS_GESTOCK_INDEX" , 

--  DDL for Index IDX_UK_STATE_NAME PARTITION "P_2018" NOCOMPRESS 

--------------------------------------------------------  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

CREATE UNIQUE INDEX "GESTOCK"."IDX_UK_STATE_NAME" ON "GESTOCK"."PRODUCT_STATES" ("STATE_NAME");  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--  DDL for Index IDX_PK_USER_STATES_STATE_ID  TABLESPACE "TBS_GESTOCK_INDEX" , 

-------------------------------------------------------- PARTITION "P_2019" NOCOMPRESS 

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_USER_STATES_STATE_ID" ON "GESTOCK"."USER_STATES" ("STATE_ID");  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--------------------------------------------------------  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--  DDL for Index IDX_PK_SALE_ID  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--------------------------------------------------------  TABLESPACE "TBS_GESTOCK_INDEX" , 

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_SALE_ID" ON "GESTOCK"."SALES" ("SALE_ID"); PARTITION "P_2020" NOCOMPRESS 

  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--  DDL for Index IDX_PK_SALE_STATE_ID  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_SALE_STATE_ID" ON "GESTOCK"."SALES_STATES" ("SALE_STATE_ID");  TABLESPACE "TBS_GESTOCK_INDEX" , 

 PARTITION "P_2021" NOCOMPRESS 

--------------------------------------------------------  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

--  DDL for Index IDX_MOVEMENTS_PRODUCT  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--------------------------------------------------------  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_PRODUCT" ON "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ("PRODUCT_ID");  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "TBS_GESTOCK_INDEX" , 

-------------------------------------------------------- PARTITION "P_2022" NOCOMPRESS 

--  DDL for Index IDX_MOVEMENTS_USER_PART (LOCAL PARTITIONED)  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_USER_PART" ON "GESTOCK"."INVENTORY_MOVEMENTS" ("USER_ID") LOCAL;  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--------------------------------------------------------  TABLESPACE "TBS_GESTOCK_INDEX" , 

--  DDL for Index IDX_SALES_USER PARTITION "P_2023" NOCOMPRESS 

--------------------------------------------------------  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

CREATE INDEX "GESTOCK"."IDX_SALES_USER" ON "GESTOCK"."SALES" ("USER_ID");  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--  DDL for Index IDX_PK_HEADER_ID  TABLESPACE "TBS_GESTOCK_INDEX" , 

-------------------------------------------------------- PARTITION "P_2024" NOCOMPRESS 

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_HEADER_ID" ON "GESTOCK"."CLOSURE_HEADER" ("HEADER_ID");  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--------------------------------------------------------  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--  DDL for Index IDX__UK_MEASUREMENT_NAME  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--------------------------------------------------------  TABLESPACE "TBS_GESTOCK_INDEX" , 

CREATE UNIQUE INDEX "GESTOCK"."IDX__UK_MEASUREMENT_NAME" ON "GESTOCK"."MEASUREMENTS_TYPES" ("MEASUREMENT_NAME"); PARTITION "P_2025" NOCOMPRESS 

  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--  DDL for Index IDX_INVENTORY_CLOSURE_LOT  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

CREATE INDEX "GESTOCK"."IDX_INVENTORY_CLOSURE_LOT" ON "GESTOCK"."INVENTORY_CLOSURE" ("LOT_ID");  TABLESPACE "TBS_GESTOCK_INDEX" , 

 PARTITION "P_FUTURE" NOCOMPRESS 

--------------------------------------------------------  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

--  DDL for Index IDX_PK_USER_ID  STORAGE(

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_USER_ID" ON "GESTOCK"."USERS" ("USER_ID");  TABLESPACE "TBS_GESTOCK_INDEX" ) ;

--------------------------------------------------------

----------------------------------------------------------  DDL for Index PK_INVENTORY_MOVEMENTS

--  DDL for Index IDX_PRODUCTS_MEASUREMENT--------------------------------------------------------

--------------------------------------------------------

CREATE INDEX "GESTOCK"."IDX_PRODUCTS_MEASUREMENT" ON "GESTOCK"."PRODUCTS" ("MEASUREMENT_ID");  CREATE UNIQUE INDEX "GESTOCK"."PK_INVENTORY_MOVEMENTS" ON "GESTOCK"."INVENTORY_MOVEMENTS" ("MOVEMENT_ID", "MOVEMENT_DATE") 

  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--  DDL for Index IDX_INVENTORY_CLOSURE_PRODUCT  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

CREATE INDEX "GESTOCK"."IDX_INVENTORY_CLOSURE_PRODUCT" ON "GESTOCK"."INVENTORY_CLOSURE" ("PRODUCT_ID");  TABLESPACE "USERS" ;

--------------------------------------------------------

----------------------------------------------------------  DDL for Index IDX_PK_LOT_ID

--  DDL for Index IDX_PK_SALE_DETAIL_ID--------------------------------------------------------

--------------------------------------------------------

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_SALE_DETAIL_ID" ON "GESTOCK"."SALE_DETAIL" ("SALE_DETAIL_ID");  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_LOT_ID" ON "GESTOCK"."BATCHES" ("LOT_ID") 

  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--  DDL for Index IDX_PK_ROLE_ID  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_ROLE_ID" ON "GESTOCK"."ROLES" ("ROLE_ID");  TABLESPACE "TBS_GESTOCK_INDEX" ;

--------------------------------------------------------

----------------------------------------------------------  DDL for Index IDX_SALES_STATE

--  DDL for Index IDX_PK_PRODUCT_ID--------------------------------------------------------

--------------------------------------------------------

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_PRODUCT_ID" ON "GESTOCK"."PRODUCTS" ("PRODUCT_ID");  CREATE INDEX "GESTOCK"."IDX_SALES_STATE" ON "GESTOCK"."SALES" ("SALE_STATE_ID") 

  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 

--------------------------------------------------------  TABLESPACE "TBS_GESTOCK_INDEX" ;

--  DDL for Index IDX_PK_INVENTORY_ID--------------------------------------------------------

----------------------------------------------------------  DDL for Index IDX_PK_CLOSURE_ID_PART

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_INVENTORY_ID" ON "GESTOCK"."INVENTORY" ("INVENTORY_ID");--------------------------------------------------------



--------------------------------------------------------  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_CLOSURE_ID_PART" ON "GESTOCK"."INVENTORY_CLOSURE" ("CLOSURE_ID") 

--  DDL for Index IDX_PRODUCTS_STATE  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

CREATE INDEX "GESTOCK"."IDX_PRODUCTS_STATE" ON "GESTOCK"."PRODUCTS" ("STATE_ID");  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--------------------------------------------------------  TABLESPACE "USERS" ;

--  DDL for Index IDX_INVENTORY_CLOSURE_USER--------------------------------------------------------

----------------------------------------------------------  DDL for Index IDX_UK_STATE_NAME

CREATE INDEX "GESTOCK"."IDX_INVENTORY_CLOSURE_USER" ON "GESTOCK"."INVENTORY_CLOSURE" ("USER_ID");--------------------------------------------------------



--------------------------------------------------------  CREATE UNIQUE INDEX "GESTOCK"."IDX_UK_STATE_NAME" ON "GESTOCK"."PRODUCT_STATES" ("STATE_NAME") 

--  DDL for Index IDX_PK_STATE_ID  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_STATE_ID" ON "GESTOCK"."PRODUCT_STATES" ("STATE_ID");  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--------------------------------------------------------  TABLESPACE "TBS_GESTOCK_INDEX" ;

--  DDL for Index IDX_UK_SALE_STATE_NAME--------------------------------------------------------

----------------------------------------------------------  DDL for Index IDX_PK_USER_STATES_STATE_ID

CREATE UNIQUE INDEX "GESTOCK"."IDX_UK_SALE_STATE_NAME" ON "GESTOCK"."SALES_STATES" ("STATE_NAME");--------------------------------------------------------



--------------------------------------------------------  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_USER_STATES_STATE_ID" ON "GESTOCK"."USER_STATES" ("STATE_ID") 

--  DDL for Index IDX_MOVEMENTS_LOT  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_LOT" ON "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ("LOT_ID");  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--------------------------------------------------------  TABLESPACE "TBS_GESTOCK_INDEX" ;

--  DDL for Index IDX_PK_CATEGORY_ID--------------------------------------------------------

----------------------------------------------------------  DDL for Index IDX_PK_SALE_ID

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_CATEGORY_ID" ON "GESTOCK"."PRODUCT_CATEGORIES" ("CATEGORY_ID");--------------------------------------------------------



--------------------------------------------------------  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_SALE_ID" ON "GESTOCK"."SALES" ("SALE_ID") 

--  DDL for Index IDX__UK_CATEGORY_NAME  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 

--------------------------------------------------------  TABLESPACE "TBS_GESTOCK_INDEX" ;

CREATE UNIQUE INDEX "GESTOCK"."IDX__UK_CATEGORY_NAME" ON "GESTOCK"."PRODUCT_CATEGORIES" ("CATEGORY_NAME");--------------------------------------------------------

--  DDL for Index IDX_PK_SALE_STATE_ID

----------------------------------------------------------------------------------------------------------------

--  DDL for Index IDX_SALEDETAIL_PRODUCT

--------------------------------------------------------  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_SALE_STATE_ID" ON "GESTOCK"."SALES_STATES" ("SALE_STATE_ID") 

CREATE INDEX "GESTOCK"."IDX_SALEDETAIL_PRODUCT" ON "GESTOCK"."SALE_DETAIL" ("PRODUCT_ID");  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 

  TABLESPACE "TBS_GESTOCK_INDEX" ;

----------------------------------------------------------------------------------------------------------------

--  DDL for Index IDX_INVENTORY_LOT--  DDL for Index IDX_MOVEMENTS_PRODUCT

----------------------------------------------------------------------------------------------------------------

CREATE INDEX "GESTOCK"."IDX_INVENTORY_LOT" ON "GESTOCK"."INVENTORY" ("LOT_ID");

  CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_PRODUCT" ON "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ("PRODUCT_ID") 

--------------------------------------------------------  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 

--  DDL for Index IDX_INVENTORY_PRODUCT  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--------------------------------------------------------  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

CREATE INDEX "GESTOCK"."IDX_INVENTORY_PRODUCT" ON "GESTOCK"."INVENTORY" ("PRODUCT_ID");  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "TBS_GESTOCK_INDEX" ;

----------------------------------------------------------------------------------------------------------------

--  DDL for Index IDX_PRODUCTS_CATEGORY--  DDL for Index IDX_MOVEMENTS_USER_PART

----------------------------------------------------------------------------------------------------------------

CREATE INDEX "GESTOCK"."IDX_PRODUCTS_CATEGORY" ON "GESTOCK"."PRODUCTS" ("CATEGORY_ID");

  CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_USER_PART" ON "GESTOCK"."INVENTORY_MOVEMENTS" ("USER_ID") 

--------------------------------------------------------  PCTFREE 10 INITRANS 2 MAXTRANS 255 

--  DDL for Index IDX_UK_USER_STATES_STATE_NAME  STORAGE(

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL

CREATE UNIQUE INDEX "GESTOCK"."IDX_UK_USER_STATES_STATE_NAME" ON "GESTOCK"."USER_STATES" ("STATE_NAME"); (PARTITION "P_2015" NOCOMPRESS 

  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--  DDL for Index IDX_MOVEMENTS_LOT_PART (LOCAL PARTITIONED)  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_LOT_PART" ON "GESTOCK"."INVENTORY_MOVEMENTS" ("LOT_ID") LOCAL;  TABLESPACE "TBS_GESTOCK_INDEX" , 

 PARTITION "P_2016" NOCOMPRESS 

--------------------------------------------------------  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

--  DDL for Index IDX_PK_CLOSURE_ID  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--------------------------------------------------------  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_CLOSURE_ID" ON "GESTOCK"."INVENTORY_CLOSURE_OLD_2" ("CLOSURE_ID");  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  TABLESPACE "TBS_GESTOCK_INDEX" , 

-------------------------------------------------------- PARTITION "P_2017" NOCOMPRESS 

--  DDL for Index IDX_SALEDETAIL_SALE  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

--------------------------------------------------------  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

CREATE INDEX "GESTOCK"."IDX_SALEDETAIL_SALE" ON "GESTOCK"."SALE_DETAIL" ("SALE_ID");  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--------------------------------------------------------  TABLESPACE "TBS_GESTOCK_INDEX" , 

--  DDL for Index IDX_PK_MEASUREMENT_ID PARTITION "P_2018" NOCOMPRESS 

--------------------------------------------------------  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_MEASUREMENT_ID" ON "GESTOCK"."MEASUREMENTS_TYPES" ("MEASUREMENT_ID");  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--------------------------------------------------------  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--  DDL for Index IDX_PK_MOVEMENT_ID  TABLESPACE "TBS_GESTOCK_INDEX" , 

-------------------------------------------------------- PARTITION "P_2019" NOCOMPRESS 

CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_MOVEMENT_ID" ON "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ("MOVEMENT_ID");  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 

  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645

--------------------------------------------------------  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1

--  DDL for Index IDX_MOVEMENTS_USER  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

--------------------------------------------------------  TABLESPACE "TBS_GESTOCK_INDEX" , 

CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_USER" ON "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ("USER_ID"); PARTITION "P_2020" NOCOMPRESS 

  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2021" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2022" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2023" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2024" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2025" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_FUTURE" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ) ;
--------------------------------------------------------
--  DDL for Index IDX_SALES_USER
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_SALES_USER" ON "GESTOCK"."SALES" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_HEADER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_HEADER_ID" ON "GESTOCK"."CLOSURE_HEADER" ("HEADER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX__UK_MEASUREMENT_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX__UK_MEASUREMENT_NAME" ON "GESTOCK"."MEASUREMENTS_TYPES" ("MEASUREMENT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_INVENTORY_CLOSURE_LOT
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_INVENTORY_CLOSURE_LOT" ON "GESTOCK"."INVENTORY_CLOSURE" ("LOT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_USER_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_USER_ID" ON "GESTOCK"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_PRODUCTS_MEASUREMENT
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_PRODUCTS_MEASUREMENT" ON "GESTOCK"."PRODUCTS" ("MEASUREMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_INVENTORY_CLOSURE_PRODUCT
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_INVENTORY_CLOSURE_PRODUCT" ON "GESTOCK"."INVENTORY_CLOSURE" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_SALE_DETAIL_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_SALE_DETAIL_ID" ON "GESTOCK"."SALE_DETAIL" ("SALE_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_ROLE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_ROLE_ID" ON "GESTOCK"."ROLES" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_PRODUCT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_PRODUCT_ID" ON "GESTOCK"."PRODUCTS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_INVENTORY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_INVENTORY_ID" ON "GESTOCK"."INVENTORY" ("INVENTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_PRODUCTS_STATE
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_PRODUCTS_STATE" ON "GESTOCK"."PRODUCTS" ("STATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_INVENTORY_CLOSURE_USER
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_INVENTORY_CLOSURE_USER" ON "GESTOCK"."INVENTORY_CLOSURE" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_STATE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_STATE_ID" ON "GESTOCK"."PRODUCT_STATES" ("STATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_UK_SALE_STATE_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_UK_SALE_STATE_NAME" ON "GESTOCK"."SALES_STATES" ("STATE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_MOVEMENTS_LOT
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_LOT" ON "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ("LOT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_CATEGORY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_CATEGORY_ID" ON "GESTOCK"."PRODUCT_CATEGORIES" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX__UK_CATEGORY_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX__UK_CATEGORY_NAME" ON "GESTOCK"."PRODUCT_CATEGORIES" ("CATEGORY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_SALEDETAIL_PRODUCT
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_SALEDETAIL_PRODUCT" ON "GESTOCK"."SALE_DETAIL" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_INVENTORY_LOT
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_INVENTORY_LOT" ON "GESTOCK"."INVENTORY" ("LOT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_INVENTORY_PRODUCT
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_INVENTORY_PRODUCT" ON "GESTOCK"."INVENTORY" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_PRODUCTS_CATEGORY
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_PRODUCTS_CATEGORY" ON "GESTOCK"."PRODUCTS" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_UK_USER_STATES_STATE_NAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_UK_USER_STATES_STATE_NAME" ON "GESTOCK"."USER_STATES" ("STATE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_MOVEMENTS_LOT_PART
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_LOT_PART" ON "GESTOCK"."INVENTORY_MOVEMENTS" ("LOT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
 (PARTITION "P_2015" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2016" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2017" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2018" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2019" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2020" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2021" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2022" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2023" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2024" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_2025" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" , 
 PARTITION "P_FUTURE" NOCOMPRESS 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ) ;
--------------------------------------------------------
--  DDL for Index IDX_PK_CLOSURE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_CLOSURE_ID" ON "GESTOCK"."INVENTORY_CLOSURE_OLD_2" ("CLOSURE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_SALEDETAIL_SALE
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_SALEDETAIL_SALE" ON "GESTOCK"."SALE_DETAIL" ("SALE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_MEASUREMENT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_MEASUREMENT_ID" ON "GESTOCK"."MEASUREMENTS_TYPES" ("MEASUREMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_PK_MOVEMENT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_MOVEMENT_ID" ON "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ("MOVEMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;
--------------------------------------------------------
--  DDL for Index IDX_MOVEMENTS_USER
--------------------------------------------------------

  CREATE INDEX "GESTOCK"."IDX_MOVEMENTS_USER" ON "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" ;