ALTER SESSION SET CONTAINER = FREEPDB1;

-- Cambiar al schema de GESTOCK
ALTER SESSION SET CURRENT_SCHEMA = GESTOCK;
--------------------------------------------------------
--  Constraints for Table INVENTORY_MOVEMENTS_NOT_PART
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" MODIFY ("MOVEMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" MODIFY ("MOVEMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ADD PRIMARY KEY ("MOVEMENT_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_MOVEMENT_ID" ON "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ("MOVEMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLOSURE_HEADER
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."CLOSURE_HEADER" MODIFY ("HEADER_ID" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."CLOSURE_HEADER" MODIFY ("CLOSURE_MONTH" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."CLOSURE_HEADER" MODIFY ("CLOSURE_YEAR" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."CLOSURE_HEADER" ADD PRIMARY KEY ("HEADER_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_HEADER_ID" ON "GESTOCK"."CLOSURE_HEADER" ("HEADER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table BATCHES
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."BATCHES" MODIFY ("ENTRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."BATCHES" MODIFY ("RFID_CODE" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."BATCHES" ADD PRIMARY KEY ("LOT_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_LOT_ID" ON "GESTOCK"."BATCHES" ("LOT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALES_STATES
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."SALES_STATES" MODIFY ("STATE_NAME" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."SALES_STATES" ADD PRIMARY KEY ("SALE_STATE_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_SALE_STATE_ID" ON "GESTOCK"."SALES_STATES" ("SALE_STATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
  ALTER TABLE "GESTOCK"."SALES_STATES" ADD UNIQUE ("STATE_NAME")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_UK_SALE_STATE_NAME" ON "GESTOCK"."SALES_STATES" ("STATE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."PRODUCT_CATEGORIES" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."PRODUCT_CATEGORIES" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_CATEGORY_ID" ON "GESTOCK"."PRODUCT_CATEGORIES" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
  ALTER TABLE "GESTOCK"."PRODUCT_CATEGORIES" ADD UNIQUE ("CATEGORY_NAME")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX__UK_CATEGORY_NAME" ON "GESTOCK"."PRODUCT_CATEGORIES" ("CATEGORY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT_STATES
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."PRODUCT_STATES" MODIFY ("STATE_NAME" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."PRODUCT_STATES" ADD PRIMARY KEY ("STATE_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_STATE_ID" ON "GESTOCK"."PRODUCT_STATES" ("STATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
  ALTER TABLE "GESTOCK"."PRODUCT_STATES" ADD UNIQUE ("STATE_NAME")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_UK_STATE_NAME" ON "GESTOCK"."PRODUCT_STATES" ("STATE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."ROLES" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."ROLES" ADD PRIMARY KEY ("ROLE_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_ROLE_ID" ON "GESTOCK"."ROLES" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEASUREMENTS_TYPES
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."MEASUREMENTS_TYPES" MODIFY ("MEASUREMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."MEASUREMENTS_TYPES" ADD PRIMARY KEY ("MEASUREMENT_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_MEASUREMENT_ID" ON "GESTOCK"."MEASUREMENTS_TYPES" ("MEASUREMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
  ALTER TABLE "GESTOCK"."MEASUREMENTS_TYPES" ADD UNIQUE ("MEASUREMENT_NAME")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX__UK_MEASUREMENT_NAME" ON "GESTOCK"."MEASUREMENTS_TYPES" ("MEASUREMENT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."INVENTORY" MODIFY ("ACTUAL_STOCK" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY" ADD PRIMARY KEY ("INVENTORY_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_INVENTORY_ID" ON "GESTOCK"."INVENTORY" ("INVENTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."PRODUCTS" MODIFY ("UNIT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."PRODUCTS" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_PRODUCT_ID" ON "GESTOCK"."PRODUCTS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_STATES
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."USER_STATES" MODIFY ("STATE_NAME" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."USER_STATES" ADD PRIMARY KEY ("STATE_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_USER_STATES_STATE_ID" ON "GESTOCK"."USER_STATES" ("STATE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
  ALTER TABLE "GESTOCK"."USER_STATES" ADD UNIQUE ("STATE_NAME")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_UK_USER_STATES_STATE_NAME" ON "GESTOCK"."USER_STATES" ("STATE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVENTORY_MOVEMENTS
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS" MODIFY ("MOVEMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS" MODIFY ("MOVEMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS" ADD CONSTRAINT "PK_INVENTORY_MOVEMENTS" PRIMARY KEY ("MOVEMENT_ID", "MOVEMENT_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."SALES" MODIFY ("SALE_DATE" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."SALES" MODIFY ("TOTAL_SALE" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."SALES" ADD PRIMARY KEY ("SALE_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_SALE_ID" ON "GESTOCK"."SALES" ("SALE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALE_DETAIL
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."SALE_DETAIL" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."SALE_DETAIL" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."SALE_DETAIL" MODIFY ("SALE_ID" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."SALE_DETAIL" MODIFY ("SUBTOTAL" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."SALE_DETAIL" MODIFY ("UNIT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."SALE_DETAIL" ADD PRIMARY KEY ("SALE_DETAIL_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_SALE_DETAIL_ID" ON "GESTOCK"."SALE_DETAIL" ("SALE_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_USER_ID" ON "GESTOCK"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVENTORY_CLOSURE_OLD_2
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."INVENTORY_CLOSURE_OLD_2" MODIFY ("CLOSURE_DATE" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY_CLOSURE_OLD_2" MODIFY ("FINAL_STOCK" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY_CLOSURE_OLD_2" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "GESTOCK"."INVENTORY_CLOSURE_OLD_2" ADD PRIMARY KEY ("CLOSURE_ID")
  USING INDEX (CREATE UNIQUE INDEX "GESTOCK"."IDX_PK_CLOSURE_ID" ON "GESTOCK"."INVENTORY_CLOSURE_OLD_2" ("CLOSURE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_GESTOCK_INDEX" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table typeorm_metadata
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."typeorm_metadata" MODIFY ("type" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLOSURE_HEADER
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."CLOSURE_HEADER" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "GESTOCK"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."INVENTORY" ADD CONSTRAINT "FK_INVENTORY_LOT" FOREIGN KEY ("LOT_ID")
	  REFERENCES "GESTOCK"."BATCHES" ("LOT_ID") ENABLE;
  ALTER TABLE "GESTOCK"."INVENTORY" ADD CONSTRAINT "FK_INVENTORY_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "GESTOCK"."PRODUCTS" ("PRODUCT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVENTORY_CLOSURE_OLD_2
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."INVENTORY_CLOSURE_OLD_2" ADD CONSTRAINT "FK_CLOSURE_LOT" FOREIGN KEY ("LOT_ID")
	  REFERENCES "GESTOCK"."BATCHES" ("LOT_ID") ENABLE;
  ALTER TABLE "GESTOCK"."INVENTORY_CLOSURE_OLD_2" ADD CONSTRAINT "FK_CLOSURE_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "GESTOCK"."PRODUCTS" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "GESTOCK"."INVENTORY_CLOSURE_OLD_2" ADD CONSTRAINT "FK_CLOSURE_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GESTOCK"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "GESTOCK"."INVENTORY_CLOSURE_OLD_2" ADD FOREIGN KEY ("HEADER_ID")
	  REFERENCES "GESTOCK"."CLOSURE_HEADER" ("HEADER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVENTORY_MOVEMENTS
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS" ADD CONSTRAINT "FK_MOVEMENTS_PRODUCT_PART" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "GESTOCK"."PRODUCTS" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS" ADD CONSTRAINT "FK_MOVEMENTS_USER_PART" FOREIGN KEY ("USER_ID")
	  REFERENCES "GESTOCK"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVENTORY_MOVEMENTS_NOT_PART
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ADD CONSTRAINT "FK_MOVEMENTS_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "GESTOCK"."PRODUCTS" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "GESTOCK"."INVENTORY_MOVEMENTS_NOT_PART" ADD CONSTRAINT "FK_MOVEMENTS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GESTOCK"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "GESTOCK"."PRODUCT_CATEGORIES" ("CATEGORY_ID") ENABLE;
  ALTER TABLE "GESTOCK"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS_MEASUREMENT" FOREIGN KEY ("MEASUREMENT_ID")
	  REFERENCES "GESTOCK"."MEASUREMENTS_TYPES" ("MEASUREMENT_ID") ENABLE;
  ALTER TABLE "GESTOCK"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS_STATE" FOREIGN KEY ("STATE_ID")
	  REFERENCES "GESTOCK"."PRODUCT_STATES" ("STATE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."SALES" ADD CONSTRAINT "FK_SALES_STATE" FOREIGN KEY ("SALE_STATE_ID")
	  REFERENCES "GESTOCK"."SALES_STATES" ("SALE_STATE_ID") ENABLE;
  ALTER TABLE "GESTOCK"."SALES" ADD CONSTRAINT "FK_SALES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GESTOCK"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALE_DETAIL
--------------------------------------------------------

  ALTER TABLE "GESTOCK"."SALE_DETAIL" ADD CONSTRAINT "FK_SALEDETAIL_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "GESTOCK"."PRODUCTS" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "GESTOCK"."SALE_DETAIL" ADD CONSTRAINT "FK_SALEDETAIL_SALE" FOREIGN KEY ("SALE_ID")
	  REFERENCES "GESTOCK"."SALES" ("SALE_ID") ENABLE;
